version: '3.7'
services:
  # server:
    # build:
       # context: server
       # dockerfile: Dockerfile-dev
    # image: wa-ud-server
    # ports:
      # - "8085:8080"
    # volumes:
      # - ../client/shared_dist:/usr/share/nginx/html
      
  # frontend:
    # stdin_open: true
    # image: node:14.5
    # command: ["/src/client/dev-node.sh"]
    # volumes:
      # - .:/src
      # - shared_dist:/src/client/dist
      # - node_modules:/src/client/node_modules
    # expose:
      # - 3000
    # ports:
      # - "3002:3000"
    # environment:
      # - CHOKIDAR_USEPOLLING=true
      
  database:
    image: mysql:8
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vizo_dashboard
      MYSQL_USER: vizomysql
      MYSQL_PASSWORD: vizomysql
    ports:
      - "3307:3306"
      
  mongodb:
    image: mongo:latest
    container_name: "vizo_mongodb"
    environment:
      MONGO_INITDB_DATABASE: vizo_sample_db
    mem_limit: 200M
    cpus: '0.25'
    volumes:
     - mongodb-data:/data/db
    ports:
      - "27017:27017"

  mysql_source:
    image: mysql:8
    container_name: "mysql_source"
    volumes:
      - ./data/mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./data/mysql/data.sql:/docker-entrypoint-initdb.d/2.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vizo_sample_mysql_db
      MYSQL_USER: vizomysql
      MYSQL_PASSWORD: vizomysql
    ports:
      - "3308:3306"

  mongo-express:
    image: mongo-express
    container_name: "vizo_mongo_express"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=rmsmongoexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=rmsmongoexpress@342
    depends_on:
      - mongodb
    ports:
      - "8888:8081" 
      
volumes:
  mongodb-data:
  dbdata:
  mysql_source_data: