CREATE TABLE IF NOT EXISTS `VIZO_ROLES` (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION varchar(255),
    NAME varchar(255)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `VIZO_USERS` (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PASSWORD varchar(255),
    USERNAME varchar(255)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `VIZO_USER_ROLES` (
        USER_ID BIGINT(20) NOT NULL,
    	ROLE_ID BIGINT(20) NOT NULL,
    	FOREIGN KEY (USER_ID) REFERENCES VIZO_USERS (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    	FOREIGN KEY (ROLE_ID) REFERENCES VIZO_ROLES (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    	PRIMARY KEY (USER_ID, ROLE_ID)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;


INSERT INTO VIZO_USERS (id, username, password) VALUES (1, 'user1', '$2a$04$Ye7/lJoJin6.m9sOJZ9ujeTgHEVM4VXgI2Ingpsnf9gXyXEXf/IlW');
INSERT INTO VIZO_USERS (id, username, password) VALUES (2, 'user2', '$2a$04$StghL1FYVyZLdi8/DIkAF./2rz61uiYPI3.MaAph5hUq03XKeflyW');
INSERT INTO VIZO_USERS (id, username, password) VALUES (3, 'user3', '$2a$04$Lk4zqXHrHd82w5/tiMy8ru9RpAXhvFfmHOuqTmFPWQcUhBD8SSJ6W');

INSERT INTO VIZO_ROLES (id, description, name) VALUES (4, 'Admin role', 'ADMIN');
INSERT INTO VIZO_ROLES (id, description, name) VALUES (5, 'User role', 'USER');

INSERT INTO VIZO_USER_ROLES (user_id, role_id) VALUES (1, 4);
INSERT INTO VIZO_USER_ROLES (user_id, role_id) VALUES (2, 5);


CREATE TABLE IF NOT EXISTS `VIZO_DATASOURCES` (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME varchar(30),
    CONNECTION_DETAILS varchar(120),
    TYPE ENUM('MONGODB', 'MYSQL', 'POSTGRESQL'),
    IS_ACTIVE boolean DEFAULT false,
    IS_CONNECTED boolean DEFAULT false,
    QUERIES INT,
    CREATED_ON timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_ID BIGINT(20) NOT NULL,
    KEY `USER_ID ` (`USER_ID `),
    CONSTRAINT `datasources_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `VIZO_USERS` (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

