export const AUTH_INIT = 'AUTH_INIT';
export const GENERATE_AUTH_TOKEN_REQUEST = 'GENERATE_AUTH_TOKEN_REQUEST';
export const GENERATE_AUTH_TOKEN_REQUEST_SUCCESS = 'GENERATE_AUTH_TOKEN_REQUEST_SUCCESS';
export const GENERATE_AUTH_TOKEN_REQUEST_ERROR = 'GENERATE_AUTH_TOKEN_REQUEST_ERROR';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_ERROR = 'AUTH_LOGOUT_ERROR';

export const GENERATE_CHART_PREVIEW = 'GENERATE_CHART_PREVIEW';
export const GENERATE_CHART_PREVIEW_SUCCESS = 'GENERATE_CHART_PREVIEW_SUCCESS';
